
services:
  server:
    volumes:
      - ./Backend:/app
      - /app/node_modules
    command: npm run dev

  client:
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
